# Generated by Django 4.1 on 2022-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tourist_is_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=255),
        ),
    ]
