# Generated by Django 4.1 on 2022-10-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_package_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
